# Generated by Django 4.0.2 on 2022-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='Not Approved', max_length=20),
        ),
    ]
