# Generated by Django 4.0.2 on 2022-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_customuser_manager_id_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='notes',
            field=models.TextField(default='Enter the note'),
        ),
    ]
